name: jumpbox
director_uuid: a30639a7-add5-43c6-a5b9-fa9c99728267
releases:
- name: jumpbox
  version: 2+dev.2

stemcells:
- alias: trusty
  os: ubuntu-trusty
  version: latest

instance_groups:
- name: jumpbox
  azs: [az1]
  instances: 1
  lifecycle: service
  jobs:
  - name: jumpbox
    release: jumpbox
    consumes: {}
    provides: {}
  - name: docker
    release: jumpbox
    consumes: {}
    provides: {}
  
  vm_type: small
  persistent_disk: 10240
  stemcell: trusty
  networks: [{name: services, static_ips: [10.1.1.191]}]
  #networks: [{name: services, default: [dns, gateway]}]
  properties:
    jumpbox:
      hostname: my-jumpbox
      users:
      - name: dev
        shell: /bin/bash
    docker:
      insecure_registries:
      - 10.1.1.102:5000
    
  env:
    bosh:
      password: "$6$4gDD3aV0rdqlrKC$2axHCxGKIObs6tAmMTqYCspcdvQXh3JJcvWOY2WGb4SrdXtnCyNaWlrf3WEqvYR2MYizEGp3kMmbpwBC6jsHt0"
    http_proxy: http://192.168.1.79:8080
    https_proxy: https://192.168.1.79:8080
    no_proxy: #List of comma-separated hosts that Docker should skip connecting to the proxy"

update:
  canaries: 1
  canary_watch_time: 1000-30000
  max_in_flight: 1
  update_watch_time: 1000-30000

